/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_testjni_cmake_JNIUtils */

#ifndef _Included_com_learn_testjni_cmake_JNIUtils
#define _Included_com_learn_testjni_cmake_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_learn_testjni_cmake_JNIUtils_number
#define com_learn_testjni_cmake_JNIUtils_number 5L
/*
 * Class:     com_learn_testjni_cmake_JNIUtils
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_testjni_1cmake_JNIUtils_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
