/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_learn_testjni_JNIUtils */

#ifndef _Included_com_learn_testjni_JNIUtils
#define _Included_com_learn_testjni_JNIUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_learn_testjni_JNIUtils
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_learn_testjni_JNIUtils_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
